superdesk/superdesk-client

app/scripts/superdesk-search/search.js
app/styles/less/sf-icons.less

Requires superdesk-sever PR: https://github.com/superdesk/superdesk-server/pull/463
Requires superdesk-api PR: https://github.com/petrjasek/superdesk-api/pull/3

Saved searches

---

app/scripts/superdesk-ingest/module.js
app/scripts/superdesk-ingest/views/settings/settings.html

[SD-1317] hide the "Rule Sets" section from Settings -> Ingest for non authorized users

(fix) SD-1317

---

app/scripts/superdesk-ingest/views/settings/ingest-rules-content.html

Requires: https://github.com/superdesk/superdesk-server/pull/472

(improvement) New Attribute of a Rule should allow empty string

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/metadata/metadata.js
app/scripts/superdesk-authoring/metadata/views/metadata-widget.html

Requires https://github.com/superdesk/superdesk-server/pull/473

(fix) SD-1320

---

app/scripts/superdesk-archive/archive-widget/baseWidget.js
app/scripts/superdesk-archive/archive-widget/item-list.html
app/scripts/superdesk-search/search.js

fix(widgets): Fix ingest and archive widgets

---

app/scripts/superdesk-desks/styles/desks.less
app/scripts/superdesk-desks/views/settings.html

This pull request also tackles the task:
[SD-1325] Add expiry time-span field per desk
Rebased on the changes regarding the task status - stage connection.

[SD-1322] Added content expiry field for the stage settings

---

app/scripts/superdesk-ingest/ingest-widget/widget-ingest.less

(fix)[widget] - Fixing the widget scroll bars.

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/tests/authoring_spec.js
app/scripts/superdesk-authoring/views/authoring.html

feat(authoring): Unlocking in authoring screen implemented.

---

app/scripts/superdesk-desks/styles/desks.less

fix(style): 'Plus' button minor fix

---

app/scripts/superdesk-dashboard/workspace-tasks/styles/tasks.less
app/scripts/superdesk-dashboard/workspace-tasks/tasks.js
app/scripts/superdesk-dashboard/workspace-tasks/views/assignee-view.html
app/scripts/superdesk-dashboard/workspace-tasks/views/kanban-board.html
app/scripts/superdesk-dashboard/workspace-tasks/views/workspace-tasks.html
app/scripts/superdesk-desks/directives.js

feat(tasks): Group tasks by status

---

app/scripts/superdesk-archive/views/package-ref.html
app/scripts/superdesk-packaging/packaging.js

feat(packages) - add remove item button

---

app/scripts/superdesk-authoring/authoring.js

fix(authoring): Fixed problems with unlocking and saving.

---

app/scripts/superdesk-dashboard/workspace-tasks/tasks.js

fix(tasks): Fix task filtering and grouping

---

app/scripts/superdesk-users/views/edit-form.html

(fix)user: fixing the user enable/disable switch.

---

app/scripts/superdesk/editor/editor.js

there is an empty paragraph that broke the loop

fix(editor): fix line/col counts when starting a new doc

---

app/index.html
app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/editor/find-replace.js
app/scripts/superdesk-authoring/editor/views/find-replace.html
app/scripts/superdesk-authoring/styles/article-edit.less
app/scripts/superdesk-authoring/widgets/widgets.js
app/scripts/superdesk/editor/editor.js
bower.json
test-main.js

updated angular because was expecting there was a bug, but that was not the case..

feat(editor): add find-replace sidebar widget

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/views/authoring.html

fix(authoring): Added error classes to input fields.

---

app/scripts/superdesk/api/url-resolver-service.js

Needs https://github.com/superdesk/superdesk-server/pull/493
SD-1385

chore(eve) - fix url resolver after Eve upgrade

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/styles/article-edit.less
app/scripts/superdesk-authoring/styles/themes.less
app/scripts/superdesk-authoring/views/authoring.html
app/scripts/superdesk-authoring/widgets/views/authoring-widgets.html
app/scripts/superdesk-authoring/widgets/widgets-article.less
app/scripts/superdesk-packaging/packaging.js
app/scripts/superdesk-packaging/packaging.less
app/scripts/superdesk-packaging/views/packaging.html
app/styles/less/variables.less

Make content responsive on 
+ Article edit screen
+ Pacakge edit screen

fix(styles): Fix widgets responsive behavior

---

app/scripts/superdesk/editor/editor.js

traverse dom to the start of current line to fix column num.

fix(editor): fix line/column counts

---

app/scripts/superdesk-packaging/packaging.js

fix(packages): Update search list after removing item from package

---

app/scripts/superdesk-archive/directives.js
app/scripts/superdesk-archive/views/item-lock.html
app/scripts/superdesk-archive/views/media-box.html
app/scripts/superdesk-archive/views/preview.html
app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/tests/authoring_spec.js
app/scripts/superdesk-authoring/views/authoring.html
app/scripts/superdesk-items-common/styles/archive-preview.less

(fix)Lock: Fixing the UI locking and unlocking based on privileges.

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/styles/themes.less
app/scripts/superdesk-authoring/views/authoring.html

and make the text bold red once it's over the limit

fix(editor): make use of soft limits only

---

app/scripts/superdesk-items-common/styles/archive-preview.less

revert styling changes from ea87b5d4b2d85ba472931492a50a1d44eb46349d

fix(styles): Revert changes for package preview

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/packages/packages.js
app/scripts/superdesk-authoring/packages/views/packages-widget.html
app/scripts/superdesk-authoring/tests/authoring_spec.js
app/scripts/superdesk-authoring/views/authoring.html
app/scripts/superdesk-authoring/views/sd-content-create.html
app/scripts/superdesk-packaging/packaging.js
app/scripts/superdesk-packaging/views/packaging.html
app/scripts/superdesk-workspace/content/content.js

SD-1373 - move create package button from widget to top app bar
SD-1380 - on + button add option to create a package

SD-1377 add + button in AES 

---

app/scripts/superdesk-authoring/editor/find-replace.js
app/scripts/superdesk-authoring/editor/views/find-replace.html
app/scripts/superdesk-authoring/widgets/views/authoring-widgets.html
app/scripts/superdesk-authoring/widgets/widgets.js
app/scripts/superdesk/editor/editor.js

after showing the highlights the focus is back on the find input field

fix(editor): return focus to find replace

---

app/scripts/superdesk/editor/editor.js

fix(authoring): Fixed closing authoring when find/replace is open.

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/views/authoring.html

feat(authoring): Added proofread mode, updated theme selector.

---

app/scripts/superdesk-dashboard/workspace-tasks/styles/tasks.less
app/scripts/superdesk-dashboard/workspace-tasks/tasks.js
app/scripts/superdesk-dashboard/workspace-tasks/views/workspace-tasks.html
app/scripts/superdesk-desks/styles/desks.less

Depends on https://github.com/superdesk/superdesk-server/pull/508

SD-1444 When a task is sent to a stage it dissapears from the Task list

---

app/scripts/superdesk-packaging/packaging.js
app/scripts/superdesk/api/http-endpoint-factory.js

fix icon for "Package item" action.

fix(patch) - remove _etag from the paylod when calling PATCH

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/styles/article-edit.less
app/scripts/superdesk-authoring/views/opened-articles.html
app/scripts/superdesk-packaging/packaging.js
app/scripts/superdesk/activity/activity-list-directive.js
app/scripts/superdesk/activity/activity.js
app/scripts/superdesk/activity/superdesk-service_spec.js
app/scripts/superdesk/activity/views/activity-list.html
app/scripts/superdesk/api/api-service.js
app/scripts/superdesk/error/error.js

so that user can open items in different browser tabs

feat(content): create links for editing

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-packaging/packaging.js
app/scripts/superdesk/api/api-service.js
app/scripts/superdesk/api/api-service_spec.js

and not inherited data from parent so it can do diff

fix(api): when doing clean return only own properties

---

app/scripts/superdesk/api/api-service.js
app/scripts/superdesk/api/http-endpoint-factory.js

I think this field also needs to be cleaned from the payload.

fix(api) - _status field needs to be cleaned from properties

---

app/scripts/superdesk/auth/auth.js

The client was never sending the delete to the server, the url it was using was not complete. We do a get to ensure that we have the correct etag.

[SD-1422] Make log out actualy send a delete to auth

---

app/scripts/superdesk-authoring/styles/themes.less
app/scripts/superdesk-authoring/views/authoring.html
app/styles/less/buttons.less

SD-1053 + general style changes

fix(styles): Proofreading toggle styling

---

app/index.html
app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/styles/article-edit.less
app/scripts/superdesk-authoring/tests/authoring_spec.js
app/scripts/superdesk-authoring/views/dashboard-articles.html
app/scripts/superdesk-authoring/views/opened-articles.html
app/scripts/superdesk-authoring/workqueue/tests/workqueue_spec.js
app/scripts/superdesk-authoring/workqueue/workqueue.js
app/scripts/superdesk-packaging/packaging.js
app/scripts/superdesk/api/api-service.js
app/scripts/superdesk/notification/notification.js
app/scripts/superdesk/services/preferencesService.js
app/scripts/superdesk/superdesk.js
test-main.js

instead of keeping an extra model that requires synchronization

refactor(workqueue): show items locked by user

---

.gitignore
app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/views/authoring.html

Depends on https://github.com/superdesk/superdesk-server/pull/512

SD-1262 Open article in read mode.

---

app/scripts/superdesk-desks/directives.js
app/scripts/superdesk-desks/views/settings.html

[SD-1449] Use global content expiry as default on stages
[SD-1450] Remove desk level content expiry

fix(stages) - Using global expiry as default for stages and removed desk level content expiry

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/views/authoring.html

The problem was in the multi session the lock message displayed was incorrectly and state of lock was not maintained.

(fix)[Lock] Fixing the lock message and remove confirmation for lock.

---

app/scripts/superdesk-archive/views/package-ref.html
app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/packages/views/packages-widget.html
app/scripts/superdesk-authoring/versioning/versions.js

fix(workqueue) - fix workqueue and versioning widget

fix(preview) - fix package preview in Ingest

---

app/scripts/superdesk-ingest/views/settings/ingest-sources-content.html
app/scripts/superdesk/directives/sdConfirm.js

fix(ingest): Fixed deleting providers twice.

---

app/scripts/superdesk-archive/module.js

feat(archive): Added fetch action to content list and search results.

---

app/scripts/superdesk-archive/views/metadata-view.html
app/scripts/superdesk-authoring/metadata/views/metadata-widget.html

fix(authoring): Added expiry data to info widget.
SD-1493

fix(archive): Fixed expiry position in metadata tab.

---

app/scripts/superdesk-archive/directives.js
app/scripts/superdesk-archive/family_spec.js
app/scripts/superdesk-archive/views/fetched-desks.html
app/scripts/superdesk-archive/views/media-box-grid.html
app/scripts/superdesk-archive/views/media-box-list.html
app/scripts/superdesk-archive/views/related-view.html
app/scripts/superdesk-search/views/search-results.html

feat(search): Added related items tab.
feat(ingest): Added "fetched in" info.
feat(search): Added "fetched in" info.
SD-1466
SD-1468
SD-1469

feat(core): Added family service.

---

app/scripts/superdesk-archive/controllers/baseList.js
app/scripts/superdesk-archive/controllers/list.js
app/scripts/superdesk-archive/views/list.html
app/scripts/superdesk-desks/directives.js

there was a scope issue so selected desk was not propagated back.

fix(desks): make desk selection propagate from directive

---

app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/views/authoring.html

fix(authoring): Fixed unlocking an item after sending it to a desk.

---

app/scripts/superdesk/services/keyboardManager.js

feat(keyboard): Added global shortcut support.

---

app/index.html
app/scripts/superdesk-authoring/authoring.js
app/scripts/superdesk-authoring/multiedit/multiedit.js
app/scripts/superdesk-authoring/multiedit/views/multiedit.html
app/scripts/superdesk-authoring/multiedit/views/sd-multiedit-article.html
app/scripts/superdesk-authoring/multiedit/views/sd-multiedit-dropdown.html
app/scripts/superdesk-authoring/styles/article-edit.less
app/scripts/superdesk-authoring/styles/multiedit.less
app/scripts/superdesk-authoring/views/authoring.html
app/scripts/superdesk-authoring/views/opened-articles.html
app/scripts/superdesk-authoring/workqueue/workqueue.js
app/styles/less/dropdowns.less
app/styles/less/navs.less
test-main.js

feat multi editing

---

AUTHORS.md

UPDATE: updated the AUTHORS list as well.

Add Peter Lamut to the Authors list

---

app/scripts/superdesk-authoring/multiedit/multiedit.js
app/scripts/superdesk-authoring/multiedit/tests/multiedit_spec.js
app/scripts/superdesk-authoring/multiedit/views/multiedit.html
app/scripts/superdesk-authoring/multiedit/views/sd-multiedit-article.html
app/scripts/superdesk-authoring/styles/multiedit.less
app/scripts/superdesk-authoring/styles/themes.less
app/scripts/superdesk-authoring/views/article-edit.html
app/scripts/superdesk-authoring/views/authoring.html
app/styles/less/buttons.less

+ take out some parts of article edit directive so that there is no save btn in authoring
+ set focus to first item when opening

feat(multiedit): let user remove an item from multiedit

---

app/scripts/superdesk-dashboard/workspace-tasks/tasks.js
app/scripts/superdesk-dashboard/workspace-tasks/views/task-preview.html
app/scripts/superdesk-dashboard/workspace-tasks/views/workspace-tasks.html
app/scripts/superdesk/ui/tests/ui_spec.js
app/scripts/superdesk/ui/ui.js
app/scripts/superdesk/ui/views/sd-timepicker-popup.html
app/scripts/superdesk/ui/views/sd-timepicker.html
app/styles/less/sf-additional.less
test-main.js

Whole `ui.js` file is different because of tab/space formatting. These are for review:
+ TimepickerDirective
+ TimepickerInnerDirective
+ TimepickerPopupDirective
+ PopupService
+ LeadingZeroFilter

feat(timepicker): Timepcker directive

---

app/scripts/superdesk-authoring/multiedit/multiedit.js
app/scripts/superdesk-authoring/multiedit/views/sd-multiedit-article.html
app/styles/less/dropdowns.less

- multiedit popup is too narrow
- make save btn disabled after saving

fix(multiedit): fix ux issues

---

app/scripts/superdesk-desks/styles/desks.less

fix(desks): Stage edit form overflow fixed

---

app/scripts/superdesk-dashboard/workspace-tasks/tasks.js
app/scripts/superdesk-desks/directives.js
app/scripts/superdesk-desks/views/settings.html

Stage edit form to show task status name instead of _id

fix(desks): Stage edit form fix
